# Generated by Django 4.0.3 on 2022-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
